export const pricingCards = [
  {
    title: 'Free',
    description: 'Perfect for trying out BookmyLead',
    price: '$0',
    duration: '',
    highlight: 'Key features',
    features: ['100 messages/month', '1 AI chatbot', '1 MB knowledge base', '5 training sources', '30-day conversation history'],
    priceId: '',
  },
  {
    title: 'Starter',
    description: 'For small businesses',
    price: '$19',
    duration: 'month',
    highlight: 'Everything in Free, plus',
    features: ['2,000 messages/month', '1 AI chatbot', '20 MB knowledge base', '15 training sources', 'Unlimited conversation history', 'Priority support'],
    priceId: 'pdt_H8UFvwsiedYbSFvkeTp3m',
    yearlyPrice: '$134',
    yearlyPriceId: 'pdt_TEMGX6k2iUz4zNq1tNtA6',
  },
  {
    title: 'Pro',
    description: 'For growing businesses',
    price: '$49',
    duration: 'month',
    highlight: 'Everything in Starter, plus',
    features: ['5,000 messages/month', '5 AI chatbots', '50 MB knowledge base', '50 training sources', 'Advanced analytics', 'Custom branding'],
    priceId: 'pdt_gfPZ5YvERGTr1bPgrrCPS',
    yearlyPrice: '$348',
    yearlyPriceId: 'pdt_RrOvAZyElPoHftofvcg2d',
  },
  {
    title: 'Business',
    description: 'The ultimate solution',
    price: '$99',
    duration: 'month',
    highlight: 'Everything in Pro, plus',
    features: ['10,000 messages/month', 'Unlimited AI chatbots', '200 MB knowledge base', 'Unlimited training sources', '24/7 Premium support', 'Custom integrations', 'White label options'],
    priceId: 'pdt_mKXy3ImVkBgEsXaKCoBAN',
    yearlyPrice: '$708',
    yearlyPriceId: 'pdt_dAXoky321LAd0qOJBX9up',
  },
]
