export const pricingCards = [
  {
    title: 'Free',
    description: 'Perfect for testing & small sites',
    price: '$0',
    duration: '',
    highlight: 'Key features',
    features: ['100 messages/month', '1 AI chatbot', '1 MB knowledge base', '5 training sources', '30-day conversation history'],
    priceId: '',
  },
  {
    title: 'Starter',
    description: 'For growing teams',
    price: '$19',
    duration: 'month',
    highlight: 'Everything in Free, plus',
    features: ['2,000 messages/month', '1 AI chatbot', '20 MB knowledge base', '15 training sources', 'Unlimited conversation history', 'Priority support'],
    // Dodo Product IDs (monthly/yearly)
    priceId: 'pdt_Gez1YlhKjDIJz3Asiql8Y',
    yearlyPrice: '$134',
    yearlyPriceId: 'pdt_4WrJSCwPMmqIAT8tVr2Kk',
  },
  {
    title: 'Pro',
    description: 'For multi-brand teams',
    price: '$49',
    duration: 'month',
    highlight: 'Everything in Starter, plus',
    features: ['5,000 messages/month', '5 AI chatbots', '50 MB knowledge base', '50 training sources', 'Advanced analytics', 'Custom branding'],
    priceId: 'pdt_VvrVsP0saqj0fjjQKVcbc',
    yearlyPrice: '$348',
    yearlyPriceId: 'pdt_suAOuFzuuXYGSntIZ8S94',
  },
  {
    title: 'Business',
    description: 'For high-volume enterprises',
    price: '$99',
    duration: 'month',
    highlight: 'Everything in Pro, plus',
    features: ['10,000 messages/month', 'Unlimited AI chatbots', '200 MB knowledge base', 'Unlimited training sources', '24/7 Premium support', 'Custom integrations', 'White label options'],
    priceId: 'pdt_2RWqgVJU6XFZ6nKQHRQez',
    yearlyPrice: '$585',
    yearlyPriceId: 'pdt_md26pGqUBcoGv8n0lWe1v',
  },
]
